# NumPy Primer - 1
- NumPy
- Arrays
    - Generating arrays
    - Data type of arrays
    - Rank & Shape of arrays

## 1. NumPy
<img src="http://www.wizdomhub.com/wp-content/uploads/2017/08/numpy_project_page.jpg" style="width: 200px"/>
- Fundamental package for scientific computing with Python. NumPy stands for "Numerical Python"
- NumPy contains...
    - a powerful N-dimensional array object
    - sophisticated (broadcasting) functions
    - tools for integrating C/C++ and Fortran code
    - useful linear algebra, Fourier transform, and random number capabilities
- Official documentation: https://docs.scipy.org/doc/numpy-1.13.0/reference/

In [1]:
# importing numpy 
# numpy is imported using alias 'np' in most cases
import numpy as np

## 2. Arrays
- NumPy arrays are similar to Python lists, but has some restrictions 
    - e.g., same data types should be inserted in each array
- Like lists, multi-dimensional arrays can be generated. But usually, less than 4-dimensional are used. 
    - Mostly 1-dimensional (vectors) or 2-dimensional (matrices) are used
    
<br>
<img src="http://community.datacamp.com.s3.amazonaws.com/community/production/ckeditor_assets/pictures/332/content_arrays-axes.png" stype= "width: 400px"/>

### Generating arrays
- from lists
- from numpy functions

In [2]:
# arrays can be generated by converting list into array
a1 = np.array([1, 2, 3])    # generate 1-D array
print(type(a1))
print(a1)

<class 'numpy.ndarray'>
[1 2 3]


In [3]:
# creating multi-dim arrays from multi-dim lists
a2 = np.array([[1, 2], [3, 4]])                    # 2-D array
print(a2)
a3 = np.array([[[1,2], [3,4]], [[5,6],[7,8]]])     # 3-D array
print(a3)

[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
# creating arrays from built-in functions
a4 = np.ones((2))          # create array with all elements equal to 1
print(a4)
a5 = np.zeros((2,3))       # create array with all element equal to 0
print(a5)
a6 = np.full((2,2), 5)     # create array with all element equal to 5
print(a6)
a7 = np.random.randn(3)   # create array with random elements (0-1)
print(a7)

[ 1.  1.]
[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[[5 5]
 [5 5]]
[ 0.37828341 -0.90292929 -0.0619987 ]


### Data type of arrays
- Most general data types for numpy numerical array are int or float
- If one wants to store string values, set ```dtype``` to ```np.str_``` or use ```np.chararray()``` 

In [7]:
a8 = np.array([1, 2, 3])          # integer array
print(a8.dtype)
a9 = np.array([1.0, 2.0, 3.0])    # float array
print(a9.dtype)

int32
float64


In [9]:
# data types can be assigned when creating array
a10 = np.array(['a'], dtype = np.int64)
print(a10)
a11 = np.array([1, 2, 3], dtype = np.float64)    # converts each value into float
print(a11)
a12 = np.array(['x', 'y', 'z'], dtype = np.str_) # creating string array
print(a12)
a13 = np.array([5, 'a'], dtype = np.object)      # inserting Python objects into array
print(a13)

ValueError: invalid literal for int() with base 10: 'a'

### Rank & Shape of arrays
- ```rank``` of array equals to number of dimensions (i.e., ```axes```) of array
    - axis
        - Each "coordinate" to index/slice array. 
        - For *n*-dimensional array, ```axes``` equal to ```{0, 1, 2, ..., n-1}```
    - Heuristically, ```rank``` equals to number of '['s in array instance
- ```shape``` of an array designates size of each dimension. 
    - In other words, how many elements fit into each axis

- For example, consider case of two-dimensional array, hence matrix.
    - ```shape``` of matrix would be ```(N, M)```. Thus ```rank``` = 2
    - Size of ```axis 0``` equals to ```N```. 
        - This means number of rows equals to ```N```.
    - Size of ```axis 1``` equals to ```M```.
        - This means number of columns equals to ```M```.

<br>    
<img src="https://www.safaribooksonline.com/library/view/elegant-scipy/9781491922927/assets/elsp_0105.png" stype= "width: 50px"/>

In [10]:
# case of 1-D array; trivial
a14 = np.array([2, 4, 6, 8, 10])
print(a14.ndim)                    # rank = 1
print(a14.shape)                   # shape = (5,)

1
(5,)


In [11]:
# case of 2-D array
a15 = np.array([[1, 2, 3], [4, 5, 6]])
print(a15.ndim)                    # rank 2
print(a15.shape)                   # shape = (2,3)

2
(2, 3)


In [12]:
# case of 3-D array
a16 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(a16.ndim)
print(a16.shape)

3
(2, 2, 2)


### Exercise 1-1.
- Create random vector (i.e., 1-D array) with length 20.
- Print ```rank```, ```shape```, and ```dtype``` of array
- Sort array in ascending order and print out result
- Sort array in descending order and print out result

In [ ]:
## Your answer

### Exercise 1-2.
- Create a 3-D array with ```shape (2, 2, 2)``` containing integers from 0 to 7
- Print ```rank```, ```shape```, and ```dtype``` of array

In [ ]:
## Your answer